config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :workspaces do
    resources :ratings
  end

  root to: "workspaces#index"

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :workspace
  belongs_to :user

  validates :wifi, inclusion: (1..5)
  validates :seating, inclusion: (1..5)
  validates :outlets, inclusion: (1..5)
  validates :noise, inclusion: (1..5)
  validates :coffee, inclusion: (1..5)

  validates :user, uniqueness: { scope: :workspace, message: "has rated this workspace already" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :workspaces
  has_many :ratings
  has_many :rated_workspaces, through: :ratings, source: :workspace

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def has_rated?(workspace)
    reviewed_workspaces.include? workspace
  end
end

app/models/workspace.rb
require 'net/http'

class Workspace < ActiveRecord::Base
  belongs_to :user

  has_many :ratings, dependent: :destroy
  validates :name, length: {minimum: 1}, uniqueness: true
  geocoded_by :name
  after_validation :geocode

  def average_rating(att)
    return "N/A" if ratings.none?
    ratings.average(att)
  end

  def overall_rating
    return "N/A" if ratings.none?
    calculate_attr_average
  end

  private

  def calculate_attr_average
    (self.average_rating(:wifi) + self.average_rating(:seating) +
      self.average_rating(:outlets) + self.average_rating(:noise) +
      self.average_rating(:coffee))/5
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def new
    @workspace = Workspace.find(params[:workspace_id])
    @rating = Rating.new
  end

  def create
    @workspace = Workspace.find(params[:workspace_id])
    @rating = @workspace.ratings.new(rating_params)

    unless @rating.save
      flash[:notice]= "You have already rated #{@workspace.name}"
    end

    redirect_to workspaces_path
  end

  def rating_params
    new_params = params.require(:rating).permit(:wifi, :seating, :outlets, :noise, :coffee)
    new_params[:user_id] = current_user.id
    new_params
  end
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @workspaces = Workspace.all
  end

  def new
    @workspace = Workspace.new

  end

  def create
    @workspace = Workspace.new(workspace_params)
      if @workspace.save
        # Workspace.get_place_id(@workspace)

    # url = URI.parse("https://maps.googleapis.com/maps/api/place/details/json?name=#{workspace_params[:name]}&types=establishment&key=AIzaSyAkk0WzkJl4oPNEYm6YbpXasQHRfHB3zSk")
    # http = Net::HTTP.new(url.host, url.port)
    # http.use_ssl = true
    # http.verify_mode = OpenSSL::SSL::VERIFY_NONE # You should use VERIFY_PEER in production
    # request = Net::HTTP::Get.new(url.request_uri)
    # res = http.request(request)
    # puts res.body


      redirect_to "/workspaces"
    else
      render "new"
    end
  end

  def show
    @workspace = Workspace.find(params[:id])
  end

  def edit
    @workspace = Workspace.find(params[:id])
  end

  def update
    @workspace = Workspace.find(params[:id])
    @workspace.update(workspace_params)
    flash[:notice] = "Edit successful"
    redirect_to workspace_path(@workspace)
  end

  def destroy
    @workspace = Workspace.find(params[:id])
    @workspace.destroy
    flash[:notice] = "Delete successful"
    redirect_to "/workspaces"
  end

  def workspace_params
    params.require(:workspace).permit(:name, :address, :latitude, :longitude)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    remainder = (5 - rating)
    "★" * rating.round + "☆" * remainder
  end
end

app/helpers/workspaces_helper.rb
module WorkspacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>FilterCoffee</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


  <!-- Bootstrap Core CSS -->
  <!-- <link href="css/bootstrap.min.css" rel="stylesheet"> -->

  <!-- Custom CSS -->
  <!-- <link href="/stylesheets/agency.css" rel="stylesheet">
  <link href="css/index.css" rel="stylesheet"> -->

  <!-- Custom Fonts -->

  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

</head>
<body>

  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header page-scroll">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand page-scroll" href="/workspaces">Filter Coffee</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  <li class="hidden">
                      <a href="#page-top"></a>
                  </li>
                  <li>
                    <%= link_to "Add A Workspace", new_workspace_path %>
                  </li>
                  <% if user_signed_in? %>
                  <li>
                      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
                  </li>
                    <% else %>
                  <li>
                    <%= link_to "Sign in", new_user_session_path %>
                  </li>
                  <li>
                      <%= link_to "Sign up", new_user_registration_path %>
                  </li>
                    <% end %>
                  <li>
                      <a class="page-scroll" href="#contact">Contact</a>
                  </li>
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
  </nav>



<p class="notice"><%= notice %> </p>
<p class="alert"><%= alert %> </p>


<%= yield %>




</body>
</html>

app/views/ratings/new.html.erb
<div class="rate">
 <div class="container">
   <div class="row">
       <div class="col-lg-12 text-center">
         <div class="workspaces-panel">
           <h2 class="section-heading">Rate This Place!</h2>
           <div class="panel-body">
           <%= form_for [@workspace, @rating] do |f| %>
             <%= f.label "WiFi rating"%>
             <%= f.select :wifi, (1..5) %>
             <%= f.label "Seating rating"%>
             <%= f.select :seating, (1..5) %>
             <%= f.label "Outlets rating"%>
             <%= f.select :outlets, (1..5) %>
             <%= f.label "Noise level rating"%>
             <%= f.select :noise, (1..5) %>
             <%= f.label "Coffee rating"%>
             <%= f.select :coffee, (1..5) %>
             <%= f.submit "Submit" %>
           <% end %>
           </div>
         </div>
       </div>
   </div>
 </div>
</div>

app/views/workspaces/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h2 class="section-heading"></h2>
            <%= form_for @workspace do |f| %>
              <%= f.label :name %>
              <%= f.text_field :name %>
              <%= f.submit %>
            <% end %>
        </div>
    </div>
</div>

app/views/workspaces/index.html.erb
<!-- Header -->
<header>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <div class="container">
        <div class="intro-text">
            <!-- <div class="intro-lead-in">Welcome To Our Studio!</div> -->
            <div class="intro-heading">Need a place to work...?</div>
            <input type="text" placeholder="find a spot..."></input>
            <button class="btn-l">Search</button>
        </div>
    </div>
</header>

<section id="cafes">
  <div class="col-md-8 venue-list">
    <ul class="venue">
      <% if @workspaces.any? %>
        <% @workspaces.each do |workspace| %>
        <li class="venue-details">
          <h2><%= link_to workspace.name, workspace_path(workspace) %></h2>
          <p><%= link_to "Rate #{workspace.name}", new_workspace_rating_path(workspace) %></p>
          <% if workspace.ratings.any? %>
            <p>Overall rating: <%= "#{star_rating(workspace.overall_rating.to_i)}" %></p>
          <% end %>
        </li>
        <% end %>
      <% else %>
      <li class="venue-details">
        <h2>No workspaces added!</h2>
        <p><%= link_to "Add a workspace!", new_workspace_path %></p>
      </li>
      <% end %>
    </ul>
  </div>
 <div class="col-md-4 map">
   <div id="map_wrapper">
      <div id="map_canvas" class="mapping"></div>
   </div>
</section>

<!-- # <%= link_to "Add a workspace", new_workspace_path %>
#
# <% if @workspaces.any? %>
#   <% @workspaces.each do |workspace| %>
#     <h2><%= link_to workspace.name, workspace_path(workspace) %></h2>
#     <%= link_to "Rate #{workspace.name}", new_workspace_rating_path(workspace) %>
#   <% end %>
# <% else %>
#   <h1> No workspaces added </h1>
# <% end %> -->

app/views/workspaces/new.html.erb
<% if @workspace.errors.any? %>
  <section id="errors" >
    <h2> <%= pluralize(@workspace.errors.count, "error") %> prohibited this workspace from being saved: </h2>
    <ul>
      <% @workspace.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>
<div class="add-place">
  <div class="container">

    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="add-place-panel">
          <h2 class="section-heading place-title">Add A Place!</h2>
          <%= form_for Workspace.new do |f| %>
            <div class="panel-body">
              <%= f.text_field :name, :class => "panel", autofocus: true, label: false, placeholder: "Location Name", input_html: { class: "input-lg" } %>
            </div>
             <div class="panel-body">
              <%= f.submit :class => "btn btn-success add-place-button", id: :submit  %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

  <input id="pac-input" class="controls" type="text"
       placeholder="Enter a location">
  <div id="map">
</div>


<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDWtGIuGMTn4AAhO1lMnyNH68UzPeffrtI&libraries=places&callback=initMap"
        async defer></script>

app/views/workspaces/show.html.erb
<div class="workspace">
  <div class="container">
      <div class="row">
          <div class="col-lg-12 text-center">
            <div class="workspaces-panel">
              <h2 class="section-heading"> Welcome to <%= @workspace.name %></h2>
                <div class="panel-body">
                 <%= link_to "Edit #{@workspace.name}", edit_workspace_path(@workspace) %>
                </div>
                <div class="panel-body">
              <%= link_to "Delete #{@workspace.name}", workspace_path(@workspace), method: :delete %>
                </div>
                <div class="panel-body">
                  <ul>
                    <p> WiFi rating: <%= star_rating(@workspace.average_rating(:wifi).to_i) %> </p>
                    <p> Seating rating: <%= star_rating(@workspace.average_rating(:seating).to_i) %> </p>
                    <p> Outlets rating: <%= star_rating(@workspace.average_rating(:outlets).to_i) %> </p>
                    <p> Noise level rating: <%= star_rating(@workspace.average_rating(:noise).to_i) %> </p>
                    <p> Coffee rating: <%= star_rating(@workspace.average_rating(:coffee).to_i) %> </p>
                  </ul>
                </div>
            </div>
          </div>
      </div>
  </div>
</div>
 